# Your workflow name.
name: Deploy to heroku

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Install Git LFS
      - name: Install Git LFS
        run: |
          apt-get update
          apt-get install -y git-lfs
          git lfs install

      # Pull LFS files
      - name: Pull LFS files
        run: git lfs pull

      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache --build-arg OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}"
          process_type: web